updated pull workflow

diff --git a/.github/workflows/pull.yml b/.github/workflows/pull.yml
--- a/.github/workflows/pull.yml
+++ b/.github/workflows/pull.yml
@@ -13,19 +13,17 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@v4
 
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-        
-      - name: Setup pnpm
-        run: npm install -g pnpm
+      - name: Setup Docker Buildx
+        uses: docker/setup-buildx-action@v2
 
-      - name: Install deps
-        run: pnpm install --frozen-lockfile
+      - name: Build and run CI containers
+        run: make ci  
 
-      - name: Run Linter
-        run: pnpm lint
-      
-      - name: Run tests
-        run: pnpm test
+      - name: Show exit code
+        run: |
+          EXIT_CODE=$(docker wait $(docker ps -q))
+          echo "Exit code: $EXIT_CODE"
+          if [ "$EXIT_CODE" -ne 0 ]; then
+            echo "Tests or lint failed"
+            exit 1
+          fi
